### ISSUE TITLE
Text orientation setting

### ISSUE THREAD

**Issue by kaiji95** [urvin-compliance/caracal#107]
Hello
How do I set the direction of the text? I want to rotate 270 degrees. The corresponding XML is
`<w:textDirection w:val="lrTbV"/>`

**Comment by jdugan** [comment]
Caracal does not support that feature right now.  

The README is comprehensive in its description of accepted parameters for each type of content.  If what you want to do is neither listed there nor demonstrated in the [sample project](https://github.com/trade-informatics/caracal-example), then you can safely assume the library does not implement that feature of OOXML.

If you're up for it, you can try tackling the problem by reviewing these [instructions](https://github.com/trade-informatics/caracal#how-to-work-on-a-problem) and maybe seeking out past PRs.  The code itself is so rigidly constructed that it tends to provide a firm framework for understanding how new parameters are included.  If not, I tend to work on issues and PRs once a month at a local meetup--but that's a couple weeks from now.  Up to you.

**Comment by kaiji95** [comment]
ok.thanks
